---
- name: Escalar un deployment en Kubernetes usando kubectl
  hosts: minikube
  become: yes
  tasks:
    - name: Escalar el deployment a 2 réplicas
      command: 'kubectl scale --replicas=2 deployment/appx-api-deployment'
      register: scale_output

    - name: Mostrar el resultado del escalado
      debug:
        var: scale_output.stdout
