---
- name: Escalar un deployment en Kubernetes usando kubectl
  hosts: minikube
  become: yes  
  tasks:
    - name: Verificar el PATH
      command: echo $PATH
      register: path_output

    - name: Configurar el PATH
      shell: echo 'export PATH=$PATH:/usr/local/bin' >> /home/infraestructura/.bashrc

    - name: Escalar el deployment a 3 réplicas
      command: /usr/local/bin/kubectl scale --replicas=3 deployment/appx-api-deployment

    - name: Mostrar el resultado del escalado
      debug:
        var: scale_output.stdout
