---
- name: Escalar un deployment en Kubernetes usando kubectl
  hosts: minikube
  become: yes  # Usa esto si necesitas permisos de superusuario
  tasks:
    - name: Escalar el deployment a 3 réplicas
      shell: kubectl scale deployment/appx-api-deployment --replicas=3
      register: scale_output

    - name: Mostrar el resultado del escalado
      debug:
        var: scale_output.stdout