- name: Instalar Docker
  yum:
    name: docker-ce
    state: present

- name: Iniciar y habilitar el servicio de Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Instalar curl
  dnf:
    name: curl
    state: present

- name: Obtener el nombre del sistema operativo
  command: uname -s
  register: uname_s

- name: Obtener la arquitectura
  command: uname -m
  register: uname_m

- name: Descargar Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Verificar la instalación de Docker Compose
  command: /usr/local/bin/docker-compose --version
  register: docker_compose_version

- name: Mostrar la versión de Docker Compose
  debug:
    var: docker_compose_version.stdout

- name: Copiar el archivo docker-compose.yml
  copy:
    src: /home/infraestructura/TP-Grupo01-Credicoop/docker-produccion/docker-compose.yml
    dest: /home/produccion/TP-Grupo01-Credicoop/docker-produccion/docker-compose.yml 

- name: Crear y levantar los contenedores de la aplicación
  command: /usr/local/bin/docker-compose up -d  
  args:
    chdir: /home/produccion/TP-Grupo01-Credicoop/docker-produccion
