---
- name: Escalar un deployment en Kubernetes usando kubectl
  hosts: minikube
  become: yes  
  tasks:
    - name: Escalar el deployment a 3 réplicas
      shell: kubectl scale --replicas=3 deployment/appx-api-deployment 
      register: scale_output

    - name: Verificar el PATH
      shell: echo $PATH
      register: path_output
      
    - debug:
          var: path_output.stdout

    - name: Mostrar el resultado del escalado
      debug:
        var: scale_output.stdout
