- name: Scale appx-api deployment in Kubernetes
  hosts: minikube
  become: yes
  tasks:
    - name: Ensure kubectl context is correct
      command: kubectl config use-context minikube

    - name: Scale the deployment
      command: kubectl scale deployment appx-api-deployment --replicas=3
      args:
        chdir: /home/produccion/TP-Grupo01-Credicoop/APPx-API/Minikube
