version: '3.8'

services:
  mediawiki:
    image: mediawiki:1.39
    ports:
      - "7000:80"
    volumes:
      - ./data:/var/www/data
      - ./localsettings:/var/www/html
    environment:
      - MEDIAWIKI_DB_TYPE=sqlite
      - MEDIAWIKI_DB_NAME=miwiki
      - MEDIAWIKI_DB_USER=
      - MEDIAWIKI_DB_PASSWORD=