version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'rootsecret'
      MYSQL_DATABASE: 'wikidb'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'wikisecret'
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - docker-produccion_default 

  mediawiki:
    image: mediawiki:1.39
    environment:
      MEDIAWIKI_DB_TYPE: 'mysql'
      MEDIAWIKI_DB_HOST: 'db'
      MEDIAWIKI_DB_NAME: 'wikidb'
      MEDIAWIKI_DB_USER: 'wikiuser'
      MEDIAWIKI_DB_PASSWORD: 'wikisecret'
      MEDIAWIKI_SITE_NAME: 'MiWiki'
      MEDIAWIKI_LANGUAGE_CODE: 'es'
      MEDIAWIKI_DEFAULT_SKIN: 'vector'
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - db
    volumes:
      - /home/produccion/TP-Grupo01-Credicoop/docker-produccion/LocalSettings.php:/var/www/html/LocalSettings.php
      - mediawiki_data:/var/www/html
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - docker-produccion_default 

volumes:
  db_data:
  mediawiki_data:

networks:
  docker-produccion_default:
