version: '3.8'

services:
  mediawiki:
    image: mediawiki:1.39.10
    ports:
      - "7000:80" # Mapea el puerto 7000 en tu máquina al puerto 80 del contenedor
    volumes:
      - ./local-settings.php:/var/www/html/LocalSettings.php # Monta tu archivo de configuración
      - ./data:/var/www/data # Persistencia de datos de SQLite
    environment:
      - MEDIAWIKI_DB_TYPE=sqlite
      - MEDIAWIKI_DB_FILE=/var/www/data/miwiki.sqlite
    restart: always
