version: '3.8'

services:
  mediawiki:
    image: mediawiki:1.39.10
    ports:
      - "7000:80" 
    volumes:
      - ./data:/var/www/data 
    environment:
      - MEDIAWIKI_DB_TYPE=sqlite
      - MEDIAWIKI_DB_FILE=/var/www/data/miwiki.sqlite
    restart: always
