version: '3.8'  

services:
  mediawiki:
    image: mediawiki:1.39  
    ports:
      - "7000:80"  
    volumes:
      - mediawiki_data:/var/www/html  
    networks:
      - mediawiki_network  

volumes:
  mediawiki_data: {}  

networks:
  mediawiki_network: {} 
