services:
  mediawiki:
    image: mediawiki:1.39
    environment:
      MEDIAWIKI_SITE_NAME: ${MEDIAWIKI_SITE_NAME}
      MEDIAWIKI_LANGUAGE_CODE: ${MEDIAWIKI_LANGUAGE_CODE}
      MEDIAWIKI_DEFAULT_SKIN: ${MEDIAWIKI_DEFAULT_SKIN}
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - mediawiki_data:/var/www/html
    networks:
      - docker-produccion_default 

volumes:
  mediawiki_data: {}

networks:
  docker-produccion_default: {}
