version: '3.8'

services:
  mediawiki:
    image: mediawiki:1.39
    environment:
      MEDIAWIKI_SITE_NAME: ${MEDIAWIKI_SITE_NAME}
      MEDIAWIKI_LANGUAGE_CODE: ${MEDIAWIKI_LANGUAGE_CODE}
      MEDIAWIKI_DEFAULT_SKIN: ${MEDIAWIKI_DEFAULT_SKIN}
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - /home/produccion/TP-Grupo01-Credicoop/docker-produccion/LocalSettings.php:/var/www/html/LocalSettings.php
      - mediawiki_data:/var/www/html
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - docker-produccion_default 

volumes:
  mediawiki_data:

networks:
  docker-produccion_default:
